name: Build & Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (none required)
        run: echo "No dependencies yet" 
      - name: Build MV3
        run: npm run build:mv3
      - name: Build MV2
        run: npm run build:mv2
      - name: List outputs
        run: |
          ls -R dist
